title: CHANGE THE WORLD FOR THE BETTER
author: Lillian Alehegn
email: lillianalehegn123@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 There are many unsolved problems around the world, let's do what we can to make it better.

# social links
twitter_username: lillianalehegn
github_username:  lillianassefa
instagram_username: lillian_a123

show_excerpts: true # set to false to remove excerpts on the homepage
